name: Linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          pip install sphinx-lint
      - name: ruff
        run: |
          ruff src/pynxtools tests
      - name: ruff formatting
        run: |
          ruff format --check src/pynxtools tests
      - name: Run Sphinx Linting
        run: |
          sphinx-lint .
