name: Check requirements

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install module
        run: |
          pip install .[fitting,testing]
      - name: Fix to dev requirements
        run: |
          python -m pip install -r requirements/dev-requirements.txt
      - name: Test with pytest
        run: |
          pytest --nbmake
